### ISSUE TITLE
Link component should detect more than just https

### ISSUE THREAD

**Issue by darr1s** [ueno-llc/ueno-gatsby-starter#7]
As title, I think <Link> component should also accepts `tel:` and `mailto:` as external link.

**Comment by jeremybarbet** [comment]
Hi!

We use this starter kit as a base for most of our projects and we often have to do this kind of change depending on our project's requirements.

Feel free to change it on your side, even though you can open a PR if you want to see it merge here.

I'm closing this issue, since it's more an improvement and not an issue
